// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "sample2.h"

namespace sample2_ns
{
  // note
  //

  const note::to_type& note::
  to () const
  {
    return this->to_.get ();
  }

  note::to_type& note::
  to ()
  {
    return this->to_.get ();
  }

  void note::
  to (const to_type& x)
  {
    this->to_.set (x);
  }

  void note::
  to (::std::unique_ptr< to_type > x)
  {
    this->to_.set (std::move (x));
  }

  const note::from_type& note::
  from () const
  {
    return this->from_.get ();
  }

  note::from_type& note::
  from ()
  {
    return this->from_.get ();
  }

  void note::
  from (const from_type& x)
  {
    this->from_.set (x);
  }

  void note::
  from (::std::unique_ptr< from_type > x)
  {
    this->from_.set (std::move (x));
  }

  const note::heading_type& note::
  heading () const
  {
    return this->heading_.get ();
  }

  note::heading_type& note::
  heading ()
  {
    return this->heading_.get ();
  }

  void note::
  heading (const heading_type& x)
  {
    this->heading_.set (x);
  }

  void note::
  heading (::std::unique_ptr< heading_type > x)
  {
    this->heading_.set (std::move (x));
  }

  const note::body_type& note::
  body () const
  {
    return this->body_.get ();
  }

  note::body_type& note::
  body ()
  {
    return this->body_.get ();
  }

  void note::
  body (const body_type& x)
  {
    this->body_.set (x);
  }

  void note::
  body (::std::unique_ptr< body_type > x)
  {
    this->body_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace sample2_ns
{
  // note
  //

  note::
  note (const to_type& to,
        const from_type& from,
        const heading_type& heading,
        const body_type& body)
  : ::xml_schema::type (),
    to_ (to, this),
    from_ (from, this),
    heading_ (heading, this),
    body_ (body, this)
  {
  }

  note::
  note (const note& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    to_ (x.to_, f, this),
    from_ (x.from_, f, this),
    heading_ (x.heading_, f, this),
    body_ (x.body_, f, this)
  {
  }

  note::
  note (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    to_ (this),
    from_ (this),
    heading_ (this),
    body_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void note::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // to
      //
      if (n.name () == "to" && n.namespace_ () == "sample2_ns")
      {
        ::std::unique_ptr< to_type > r (
          to_traits::create (i, f, this));

        if (!to_.present ())
        {
          this->to_.set (::std::move (r));
          continue;
        }
      }

      // from
      //
      if (n.name () == "from" && n.namespace_ () == "sample2_ns")
      {
        ::std::unique_ptr< from_type > r (
          from_traits::create (i, f, this));

        if (!from_.present ())
        {
          this->from_.set (::std::move (r));
          continue;
        }
      }

      // heading
      //
      if (n.name () == "heading" && n.namespace_ () == "sample2_ns")
      {
        ::std::unique_ptr< heading_type > r (
          heading_traits::create (i, f, this));

        if (!heading_.present ())
        {
          this->heading_.set (::std::move (r));
          continue;
        }
      }

      // body
      //
      if (n.name () == "body" && n.namespace_ () == "sample2_ns")
      {
        ::std::unique_ptr< body_type > r (
          body_traits::create (i, f, this));

        if (!body_.present ())
        {
          this->body_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!to_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "to",
        "sample2_ns");
    }

    if (!from_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "from",
        "sample2_ns");
    }

    if (!heading_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "heading",
        "sample2_ns");
    }

    if (!body_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "body",
        "sample2_ns");
    }
  }

  note* note::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class note (*this, f, c);
  }

  note& note::
  operator= (const note& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->to_ = x.to_;
      this->from_ = x.from_;
      this->heading_ = x.heading_;
      this->body_ = x.body_;
    }

    return *this;
  }

  note::
  ~note ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace sample2_ns
{
  ::std::unique_ptr< ::sample2_ns::note >
  note_ (const ::std::string& u,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (const ::std::string& u,
         ::xml_schema::error_handler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (const ::std::string& u,
         ::xercesc::DOMErrorHandler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sample2_ns::note_ (isrc, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         ::xml_schema::error_handler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sample2_ns::note_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         ::xercesc::DOMErrorHandler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::sample2_ns::note_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         const ::std::string& sid,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sample2_ns::note_ (isrc, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         const ::std::string& sid,
         ::xml_schema::error_handler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sample2_ns::note_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::std::istream& is,
         const ::std::string& sid,
         ::xercesc::DOMErrorHandler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::sample2_ns::note_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::xercesc::InputSource& i,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::xercesc::InputSource& i,
         ::xml_schema::error_handler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::xercesc::InputSource& i,
         ::xercesc::DOMErrorHandler& h,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::sample2_ns::note > (
      ::sample2_ns::note_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (const ::xercesc::DOMDocument& doc,
         ::xml_schema::flags f,
         const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::unique_ptr< ::sample2_ns::note > (
        ::sample2_ns::note_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "note" &&
        n.namespace_ () == "sample2_ns")
    {
      ::std::unique_ptr< ::sample2_ns::note > r (
        ::xsd::cxx::tree::traits< ::sample2_ns::note, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "note",
      "sample2_ns");
  }

  ::std::unique_ptr< ::sample2_ns::note >
  note_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
         ::xml_schema::flags f,
         const ::xml_schema::properties&)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "note" &&
        n.namespace_ () == "sample2_ns")
    {
      ::std::unique_ptr< ::sample2_ns::note > r (
        ::xsd::cxx::tree::traits< ::sample2_ns::note, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "note",
      "sample2_ns");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

